### ISSUE TITLE
website

### ISSUE THREAD

**Issue by rebecajohn** [the-chen-lab/data-addition-dilemma#1]
Where can i find the paper in proceedings in MLR website ?

**Comment by irenetrampoline** [comment]
The paper was published at MLHC 2024 which will publish in Proceedings of Machine Learning Research (JMLR Proceedings track). The conference happened in June, and usually there's a 3-6 month delay in getting it out through PMLR. Stay tuned!

https://www.mlforhc.org/paper-submission
